services:
  - type: web
    name: sea-lion-code-review
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: SEA_LION_API_KEY   # paste your key in Render dashboard
        sync: false
